require File.join(File.expand_path(File.dirname(__FILE__)), 'diarize', 'lium.rb')
require File.join(File.expand_path(File.dirname(__FILE__)), 'diarize', 'audio.rb')
require File.join(File.expand_path(File.dirname(__FILE__)), 'diarize', 'segment.rb')
require File.join(File.expand_path(File.dirname(__FILE__)), 'diarize', 'segmentation.rb')
require File.join(File.expand_path(File.dirname(__FILE__)), 'diarize', 'audio_player.rb')
